services:
  database:
    image: mysql:8
    container_name: forum_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forum
    volumes:
      - forum_db_data:/var/lib/mysql
    networks:
      - forum_net

  app:
    build: .
    container_name: forum_app
    ports:
      - "80:80"
    environment:
      - PORT=80
      - HOST=0.0.0.0
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=forum
    depends_on:
      - database
    networks:
      - forum_net

networks:
  forum_net:
    driver: bridge

volumes:
  forum_db_data:
